language: node_js

node_js:
   - "0.10"

env:
  global:
  - ARTIFACTS_S3_BUCKET=P1Dashboard

install:
   - npm install

before_script:
   - npm install -g grunt-cli
   - npm install grunt-contrib-jasmine

script: grunt travis
